---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/categories":
    get:
      summary: list categories
      responses:
        '200':
          description: successful
  "/meals?category={category}":
    parameters:
    - name: category
      in: path
      description: category name to be searched
      required: true
      schema:
        type: string
    get:
      summary: list meals
      responses:
        '200':
          description: successful
  "/meals/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show meal
      responses:
        '200':
          description: successful
